#!/bin/bash
if [ $# -lt 1 ]; then
    echo "$0: stdin"
    let cnt=0
    while read line; do
        let cnt+=1
        echo "$cnt $line"
#       sleep 1
    done
else
    echo "$0: $1"
        let cnt=0
    while read line; do
        let cnt+=1
        echo "$cnt $line"
#       sleep 1
    done <$1
fi
